[package]
name = "single-event-upset-detector"
version = "0.1.0"
authors = ["Colemanator <peter.coleman@rexsoftware.com.au>"]
edition = "2018"

[dependencies]
core_simd = { git = "https://github.com/rust-lang/portable-simd" }
structopt = "0.3"